src/AppBundle/Entity/Book.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity
 * @ORM\Table(name="`book`")
 * @Vich\Uploadable
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string")
     */
    private $title;

    /**
     * @ORM\Column(type="string")
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Genre")
     * @ORM\JoinColumn(name="genre", referencedColumnName="id")
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=5000)
     */
    private $synopsis;

    /**
     * @ORM\Column(type="string")
     *
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="book_images", fileNameProperty="image")
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string")
     *
     * @Assert\Isbn(
     *     type="isbn10",
     *     message="Invalid Isbn provided!"
     * )
     */
    private $isbn;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $publisher;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $publish_date;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_added;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $google_api;

    /**
     * @return mixed
     */
    public function getGoogleApi()
    {
        return $this->google_api;
    }

    /**
     * @param mixed $google_api
     */
    public function setGoogleApi($google_api)
    {
        $this->google_api = $google_api;
    }

    public function __construct()
    {
        $this->date_added = new \DateTime();
    }

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * @param mixed $title
     */
    public function setTitle($title)
    {
        $this->title = $title;
    }

    /**
     * @return mixed
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param mixed $author
     */
    public function setAuthor($author)
    {
        $this->author = $author;
    }

    /**
     * @return mixed
     */
    public function getGenre()
    {
        return $this->genre;
    }

    /**
     * @param mixed $genre
     */
    public function setGenre($genre)
    {
        $this->genre = $genre;
    }

    /**
     * @return mixed
     */
    public function getSynopsis()
    {
        return $this->synopsis;
    }

    /**
     * @param mixed $synopsis
     */
    public function setSynopsis($synopsis)
    {
        $this->synopsis = $synopsis;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param mixed $image
     */
    public function setImage($image)
    {
        $this->image = $image;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param File $imageFile
     */
    public function setImageFile(File $imageFile = null)
    {
        $this->imageFile = $imageFile;
    }

    /**
     * @return mixed
     */
    public function getIsbn()
    {
        return $this->isbn;
    }

    /**
     * @param mixed $isbn
     */
    public function setIsbn($isbn)
    {
        $this->isbn = $isbn;
    }

    /**
     * @return mixed
     */
    public function getPublisher()
    {
        return $this->publisher;
    }

    /**
     * @param mixed $publisher
     */
    public function setPublisher($publisher)
    {
        $this->publisher = $publisher;
    }

    /**
     * @return mixed
     */
    public function getPublishDate()
    {
        return $this->publish_date;
    }

    /**
     * @param mixed $publish_date
     */
    public function setPublishDate($publish_date)
    {
        $this->publish_date = $publish_date;
    }

    /**
     * @return mixed
     */
    public function getDateAdded()
    {
        return $this->date_added;
    }

    /**
     * @param mixed $date_added
     */
    public function setDateAdded($date_added)
    {
        $this->date_added = $date_added;
    }

    public function __toString()
    {
        return (string) $this->id;
    }
}

src/AppBundle/Entity/Review.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="`review`")
 */
class Review
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user_id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Book")
     * @ORM\JoinColumn(name="book_id", referencedColumnName="id")
     */
    private $book_id;

    /**
     * @ORM\Column(type="float")
     */
    private $rating;

    /**
     * @ORM\Column(type="string")
     */
    private $review;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $soft_delete;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * @param mixed $user_id
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;
    }

    /**
     * @return mixed
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * @param mixed $rating
     */
    public function setRating($rating)
    {
        $this->rating = $rating;
    }

    /**
     * @return mixed
     */
    public function getReview()
    {
        return $this->review;
    }

    /**
     * @param mixed $review
     */
    public function setReview($review)
    {
        $this->review = $review;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getBookId()
    {
        return $this->book_id;
    }

    /**
     * @param mixed $book_id
     */
    public function setBookId($book_id)
    {
        $this->book_id = $book_id;
    }

    /**
     * @return boolean
     */
    public function getSoftDelete()
    {
        return $this->soft_delete;
    }

    /**
     * @param boolean $soft_delete
     */
    public function setSoftDelete($soft_delete)
    {
        $this->soft_delete = $soft_delete;
    }
}

src/AppBundle/Resources/views/Room/allreviews.html.twig
{% extends 'base.html.twig' %}

{% block title %}all reviews{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">All Reviews</h1>
        </div>
    </div>
    {% if reviews is empty %}
        <h3 class="text-center">There are no reviews for this book yet.</h3>
    {% else %}
        {% for review in reviews %}
            <div class="col-md-10">
                <p><i class="fa fa-2x fa-user"></i> {{ review.userId.username }}</p>
                <p>Date: {{ review.date|date("m/d/Y") }}</p>
                {{ review.rating|rating }}
                <p><strong>Comment:</strong></p>
                <p>{{ review.review }}</p>
            </div>
            {% if is_granted('ROLE_MODERATOR') %}
                <div class="col-md-2 text-center">
                    <form method="post" action="{{ path('delete_review') }}">
                        <input type="hidden" name="id" value="{{ review.id }}">
                        <input type="hidden" name="bookId" value="{{ review.bookId }}">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}

src/AppBundle/Resources/views/Room/bookAddedSuccessfully.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adding new book{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">Book was added successfully</h1>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Room/bookView.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book Review{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">{{ bookInfo.title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            {% if bookInfo.googleApi %}
            <img
                class="center-block img-responsive"
                src="{{ bookInfo.image }}"
                alt="{{ bookInfo.title }} book cover"
            >
            {% else %}
                <img
                        class="center-block img-responsive"
                        src="{{ asset('uploads/book_covers/' ~ bookInfo.image) }}"
                        alt="{{ bookInfo.title }} book cover"
                >
            {% endif %}
        </div>
        <div class="col-lg-5">
            <h4>Synopsis:</h4>
            <p>{{ bookInfo.synopsis }}</p>
        </div>
        <div class="col-lg-3">
            <table class="table table-condensed">
                <thead class="">
                    <th class="text-center"><h3>Product Details</h3></th>
                </thead>
                <tbody>
                    <tr>
                        <td><strong>ISBN:</strong> {{ bookInfo.isbn }}</td>
                    </tr>
                    <tr>
                        <td><strong>Publisher:</strong> {{ bookInfo.publisher }}</td>
                    </tr>
                    <tr>
                        <td><strong>Publish date:</strong> {{ bookInfo.publishDate|date("m/d/Y") }}</td>
                    </tr>
                    <tr>
                        <td><strong>Google Rating:</strong> {{ googleRating }} / 5</td>
                    </tr>
                    <tr>
                        <td><strong>Price:</strong>£{{ amount }}</td>
                    </tr>
                    <tr>
                        <td><strong>Buy Link:</strong><a href="{{ buyingLink }}">{{ buyingLink }}</a></td>
                    </tr>
                </tbody>
            </table>
            <table class="table table-condensed">
                <thead class="">
                <th class="text-center"><h4>Average Rating</h4></th>
                </thead>
                <tbody>
                <tr>
                    <td class="text-center"> {{ avgRating|rating }}</td>
                </tr>
                <tr>
                    <td><a class="btn btn-primary btn-lg center-block" href="{{ path('book_user_review', {'bookId': bookInfo.id}) }}">Rate & Review</a></td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <h1><strong>5 most recent reviews</strong></h1>
            <h4>To view all reviews click <a href="{{ path('book_all_reviews', {'bookId': bookInfo.id}) }}">here</a> </h4>
                {% if reviews is empty %}
                    <h3>There are no reviews for this book yet.</h3>
                {% else %}
                {% for review in reviews %}
                    <div class="col-md-10">
                    <p><i class="fa fa-2x fa-user"></i> {{ review.userId.username }} - {{ review.date|date("m/d/Y") }}</p>
                    {{ review.rating|rating }}
                    <p><strong>Comment:</strong></p>
                    <p>{{ review.review }}</p>
                    </div>
                    <hr>
                {% endfor %}
                {% endif %}
            </div>
    </div>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Room/booksFromSearch.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adding new book{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">Books returned from search</h1>
            <p>Shows all the books returned from search.</p>
        </div>
    </div>

    {% if books is empty %}
        <h2>No Books where found from the search</h2>
    {% else %}
        <div class="row">
        {% for book in books %}
            <div class="col-sm-3">
                <figure>
                    <a href="{{
                        path('book_search_view', {
                            'isbn': book.isbn,
                            'title': book.title,
                            'publishDate' : book.publishDate,
                            'publisher' : book.publisher,
                            'author' : book.author,
                            'description' : book.description,
                            'categories' : book.categories,
                            'coverUrl' : book.coverUrl,
                        }) }}" >
                        <img
                                style=""
                                class="center-block"
                                src="{{ book.coverUrl }}"
                                alt="{{ book.title }} book cover"
                        >
                    </a>
                    <figcaption class="text-center">{{ book.title }}</figcaption>
                </figure>
            </div>
        {% endfor %}
        </div>
    {% endif %}

{% endblock %}

src/AppBundle/Resources/views/Room/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adding new book{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">Add new book</h1>
            <p>Add a new book, so others can review it.</p>
        </div>
    </div>

    {% if app.session.flashBag.has('success') %}
        <div class="alert alert-success">
            {% for msg in app.session.flashBag.get('success') %}
                {{ msg }}
            {% endfor %}
        </div>
    {% endif %}

    {{ form_start(form) }}
    {{ form_row(form._token) }}

    {% if not form.vars.valid %}
        <div class="alert alert-danger">
            {{ form_errors(form.isbn) }}
            {{ form_errors(form.image) }}
         </div>
    {% endif %}

    <div class="col-lg-12">
        <div class="form-group">
            {{ form_label(form.title) }}
            {{ form_widget(form.title, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>

        <div class="form-group">
            {{ form_label(form.author) }}
            {{ form_widget(form.author, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
        <div class="form-group">
            {{ form_label(form.synopsis) }}
            {{ form_widget(form.synopsis, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
        <div class="form-group">
            {{ form_label(form.genre) }}
            {{ form_widget(form.genre, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
            <div class="form-group">
                {{ form_label(form.image) }}
                {{ form_widget(form.image) }}
            </div>
        <div class="form-group">
            {{ form_label(form.isbn) }}
            {{ form_widget(form.isbn, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
        <div class="form-group">
            {{ form_label(form.publisher) }}
            {{ form_widget(form.publisher, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
        <div class="form-group">
            {{ form_label(form.format) }}
            {{ form_widget(form.format, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
        <div class="form-group">
            {{ form_label(form.pages) }}
            {{ form_widget(form.pages, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
            <div class="form-group">
                {{ form_row(form.publishDate) }}
            </div>

        {{ form_widget(form.submit, { 'attr': {
            'class' : 'btn btn-lg btn-default',
        }} ) }}
    </div>

    {{ form_start(form) }}
{% endblock %}

src/AppBundle/Resources/views/Room/genre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">Book Genres</h1>
            <p>Choose from your favourite book genres</p>
        </div>
    {% for genre in genreArray %}
        <div class="col-md-4 text-center">
            <a style="margin: 5px; width: 80%" type="button" class="btn btn-default" href="{{ path('book_genre_view', {'id':genre.id}) }}">{{ genre.genre }}</a>
        </div>
    {% endfor %}
    </div>
{% endblock %}

src/AppBundle/Resources/views/Room/genreView.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books View{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">{{ genre }}</h1>
            <p>Leave a review on your favourite {{ genre }} books.</p>
        </div>
    </div>
    <div class="row">
        {% for book in pagination %}
            <div class="col-sm-3">
                <figure>
                    <a href="{{ path('book_review', {'bookId': book.id}) }}" >
                        <img
                                style=""
                                class="img-responsive"
                                src="{{ asset('uploads/book_covers/' ~ book.image) }}"
                                alt="{{ book.title }} book cover"
                        >
                    </a>
                    <figcaption class="text-center">{{ book.title }}</figcaption>
                </figure>
            </div>
        {% endfor %}
    </div>
    {# display navigation #}
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}

src/AppBundle/Resources/views/Room/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books View{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">Books</h1>
            <p>These all are all we have to offer.</p>
        </div>
    </div>

    <hr>

    <div class="row">
        {% for book in pagination %}
            <div class="col-sm-3">
                <figure>
                    <a href="{{ path('book_review', {'bookId': book.id}) }}" >
                        {% if book.googleApi %}
                            <img
                                    class="center-block img-responsive"
                                    src="{{ book.image }}"
                                    alt="{{ book.title }} book cover"
                            >
                        {% else %}
                            <img
                                    class="center-block img-responsive"
                                    src="{{ asset('uploads/book_covers/' ~ book.image) }}"
                                    alt="{{ book.title }} book cover"
                            >
                        {% endif %}
                    </a>
                    <figcaption class="text-center">{{ book.title }}</figcaption>
                </figure>
            </div>
        {% endfor %}
    </div>
    {# display navigation #}
    <div class="navigation">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}

src/AppBundle/Resources/views/Room/searchBookFromISBN.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adding new book{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">Add Book with ISBN</h1>
            <p>Add a new book, so others can review it.</p>
        </div>
    </div>

    {% if app.session.flashBag.has('success') %}
        <div class="alert alert-success">
            {% for msg in app.session.flashBag.get('success') %}
                {{ msg }}
            {% endfor %}
        </div>
    {% endif %}

    {{ form_start(form,{'attr':
        {
            'action' : path('book_search_result')
        }} ) }}
    {{ form_row(form._token) }}

    {% if not form.vars.valid %}
        <div class="alert alert-danger">
            {{ form_errors(form.isbn) }}
        </div>
    {% endif %}

    <div class="col-lg-6">
        <div class="form-group">
            {{ form_label(form.isbn) }}
            {{ form_widget(form.isbn, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
        <div class="form-group">
            {{ form_label(form.submit) }}
            {{ form_widget(form.submit, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
    </div>

    {{ form_start(form) }}

{% endblock %}

src/AppBundle/Resources/views/Room/searchBookFromTitle.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adding new book{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">Add Book with ISBN</h1>
            <p>Add a new book, so others can review it.</p>
        </div>
    </div>

    {% if app.session.flashBag.has('success') %}
        <div class="alert alert-success">
            {% for msg in app.session.flashBag.get('success') %}
                {{ msg }}
            {% endfor %}
        </div>
    {% endif %}

    {{ form_start(form,{'attr':
        {
            'action' : path('book_search_result')
        }} ) }}
    {{ form_row(form._token) }}

    {% if not form.vars.valid %}
        <div class="alert alert-danger">
            {{ form_errors(form.title) }}
        </div>
    {% endif %}

    <div class="col-lg-6">
        <div class="form-group">
            {{ form_label(form.title) }}
            {{ form_widget(form.title, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
        <div class="form-group">
            {{ form_label(form.submit) }}
            {{ form_widget(form.submit, { 'attr': {
                'class' : 'form-control',
            }} ) }}
        </div>
    </div>

    {{ form_start(form) }}

{% endblock %}

src/AppBundle/Resources/views/Room/usereview.html.twig
{% extends 'base.html.twig' %}

{% block title %}user review{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">Leave a Review</h1>
            <p>Tell us how you found this book. Please be honest.</p>
        </div>
    </div>
    <hr>
    {{ form_start(form) }}

    <div class="text-center">
        <div>
            <h2>{{ form_label(form.rating) }}</h2>
            {{ form_widget(form.rating) }}
        </div>

        <div class="text-center">
            <h2>{{ form_label(form.review) }}</h2>
            {{ form_widget(form.review, { 'attr': {
                'style' : 'width:80%',
                'rows' : '4',
             }} ) }}
        </div>

         <div class="btn">
            {{ form_row(form.sumbit) }}
         </div>
    </div>
    {{ form_end(form) }}

{% endblock %}

src/AppBundle/Resources/views/Room/viewFromSearch.html.twig
{% extends 'base.html.twig' %}

{% block title %}Adding new book{% endblock %}

{% block body %}
    <div class="container">
        <div class="jumbotron; text-center">
            <h1 style="text-align: center">{{ title }}</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4">
            <img
                    class="center-block img-responsive"
                    src="{{ coverURl }}"
                    alt="{{ title }} book cover"
            >
        </div>
        <div class="col-lg-5">
            <h4>Synopsis:</h4>
            <p>{{ description }}</p>
        </div>
        <div class="col-lg-3">
            <table class="table table-condensed">
                <thead class="">
                <th class="text-center"><h3>Product Details</h3></th>
                </thead>
                <tbody>
                <tr>
                    <td><strong>ISBN:</strong> {{ isbn }}</td>
                </tr>
                <tr>
                    <td><strong>Publisher:</strong> {{ publisher }}</td>
                </tr>
                <tr>
                    <td><strong>Publish date:</strong> {{ publishDate }}</td>
                </tr>
                <tr>
                    <td><strong>Genre:</strong> {{ categories }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="text-center">
        <a class="btn btn-primary" href="{{
        path('book_search_add', {
            'isbn': isbn,
            'title': title,
            'publishDate' : publishDate,
            'publisher' : publisher,
            'author' : author,
            'synopsis' : description,
            'genre' : categories,
            'image' : coverURl,
        }) }}">
            Add Book
        </a>
    </div>
{% endblock %}